name: flutter_app_template
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1

  # Logger
  simple_logger:

  # LocalDatabase
  shared_preferences:

  # Riverpod
  hooks_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Hooks
  flutter_hooks: ^0.20.4

  # Entity
  freezed_annotation:
  json_annotation: ^4.8.1
  equatable:

  # Dialog
  adaptive_dialog:

  # Access local storage
  path_provider:

  # Date
  intl:

  # Reactive
  rxdart:

  # Data share
  share_plus:

  # WebView
  flutter_inappwebview: ^6.0.0

  # Launcher
  url_launcher:
  map_launcher:

  # Transition
  page_transition:

  # Image
  image_picker:
  image_gallery_saver:
  image_cropper:
  flutter_image_compress:
  extended_image:
  flutter_svg:

  # Picker
  numberpicker:

  # PullToRefresh
  pull_to_refresh_flutter3:

  # Permission
  permission_handler:

  # Firebase
  firebase_core: ^2.27.1
  firebase_analytics: ^10.8.10
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_storage: ^11.6.10
  cloud_functions: ^4.6.9
  firebase_messaging: ^14.7.20
  firebase_crashlytics: ^3.4.19
  firebase_remote_config: ^4.4.1

  # LocalNotification
  flutter_local_notifications:
  flutter_timezone: ^1.0.8
  timezone:

  # Api
  retrofit:
  dio:

  # Navigation
  go_router: ^12.1.1

  # Info
  package_info_plus:
  device_info_plus:

  # Text
  flutter_linkify:

  # Widget
  flutter_slidable:
  dismissible_page:

  # Other
  uuid:
  synchronized:
  hashids2:
  collection:
  quiver:
  html:
  analyzer: ^6.4.1
  google_mobile_ads: ^5.0.0
  version: ^3.0.2

dev_dependencies:
  # Test
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito:

  # Static analysis
  pedantic_mono: ^1.25.0
  custom_lint:
  riverpod_lint:

  # Serializer
  json_serializable:

  # Code generator
  build_runner: ^2.4.8
  freezed:
  flutter_gen_runner:
  retrofit_generator:
  riverpod_generator:

  # Other
  flutter_launcher_icons:
  change_app_package_name: ^1.1.0

flutter_gen:
  output: lib/core/res/gen/
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/

  # カスタムフォントを利用する場合はここを設定する
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_launcher_iconsを利用してアイコンのリサイズする場合はここを設定する
#flutter_icons:
#  android: true
#  ios: true
#  image_path_android: "assets/icon/icon_android.png"
#  image_path_ios: "assets/icon/icon_ios.png"
#  adaptive_icon_foreground: "assets/icon/adaptive_icon_foreground.png"
#  adaptive_icon_background: "#F4A281"

